// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umkjtsnfbtbfrrchsybd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVta2p0c25mYnRiZnJyY2hzeWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjUwNjIsImV4cCI6MjA2MzU0MTA2Mn0.KoXj2IfNPOFkxzUuxjXVbMT8u9hsWVJg-Aea49e_muI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);